# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.recordingLabel = QtWidgets.QLabel(self.centralwidget)
        self.recordingLabel.setGeometry(QtCore.QRect(100, 130, 300, 111))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.recordingLabel.setFont(font)
        self.recordingLabel.setStyleSheet("background-color: rgba(242,242,242, 0.7);\n"
"border-radius: 10px")
        self.recordingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recordingLabel.setObjectName("recordingLabel")
        self.editLabel = QtWidgets.QLabel(self.centralwidget)
        self.editLabel.setGeometry(QtCore.QRect(600, 150, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.editLabel.setFont(font)
        self.editLabel.setStyleSheet("background-color: rgba(242,242,242, 0.7);\n"
"border-radius: 10px")
        self.editLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.editLabel.setObjectName("editLabel")
        self.recordingButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordingButton.setGeometry(QtCore.QRect(140, 320, 220, 220))
        self.recordingButton.setStyleSheet("background-color: #f2f2f2;\n"
"border-radius: 20px")
        self.recordingButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/microphone_normal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("imgs/microphone_click.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("imgs/microphone_click.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.recordingButton.setIcon(icon)
        self.recordingButton.setIconSize(QtCore.QSize(200, 200))
        self.recordingButton.setObjectName("recordingButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(640, 320, 220, 220))
        self.editButton.setStyleSheet("background-color: #f2f2f2;\n"
"border-radius: 20px")
        self.editButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/sound_normal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("imgs/sound_click.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("imgs/sound_click.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.editButton.setIcon(icon1)
        self.editButton.setIconSize(QtCore.QSize(200, 200))
        self.editButton.setAutoDefault(False)
        self.editButton.setObjectName("editButton")
        self.bgLabel = QtWidgets.QLabel(self.centralwidget)
        self.bgLabel.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.bgLabel.setText("")
        self.bgLabel.setPixmap(QtGui.QPixmap("imgs/bg.jpg"))
        self.bgLabel.setScaledContents(False)
        self.bgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bgLabel.setObjectName("bgLabel")
        self.bgLabel.raise_()
        self.recordingLabel.raise_()
        self.editLabel.raise_()
        self.recordingButton.raise_()
        self.editButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recordingLabel.setText(_translate("MainWindow", "<html><head/><body><p>START</p><p>RECORDING</p></body></html>"))
        self.editLabel.setText(_translate("MainWindow", "EDIT AUDIO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
